# ==============================================================================
# 
#   B A S E    P A G E     C O N F I G U R A T I O N
# 
# ==============================================================================
- title: <span class="display-4">Bootwrap</span>
  description: 
    - <h2 class="text-muted">Pure Python wrapper for one of the most popular front-end toolkit Bootstrap, allowing quick and easy prototyping of web-based user interfaces</h2>
  image:
    file: flash.png
    height: 300

- title: Installation
  description: 
    - "Use the following command to install Python Bootwrap (<span class='text-danger'>Please note, the PIP install is currently unavailable. The first version of Python Bootstrap should be released toward the end of March 2021.</span>)"
  code:
    ~$ pip install bootwrap

- title: Single-Page Application
  description:
    - "A single-page Bootwrap application looks something like this:"
  code: |
    @left
    from flask import Flask, Markup
    from bootwrap import Page, Text

    app = Flask(__name__)

    @app.route('/')
    def hello_world():
        return Markup(
            Page(container=[Text('Hello Word!')])
        )
            
    if __name__ == '__main__':
        app.run(debug=True)
  image:
    file: single-page-app.png
    height: 200

- title: Multi-Pages Application
  description:
    - "A multi-pages Bootwrap application looks something like this:"
  code: |
    @left
    from flask import Flask, Markup
    from bootwrap import (
      Page, Menu, Image, Anchor, Button, Text
    )

    # Both 'logo.png' and 'favicon.ico' are
    # stored in 'docs' folder
    app = Flask(
      __name__,
      static_folder='docs',
      static_url_path=''
    )

    class MyMenu(Menu):
        def __init__(self):
            super().__init__(
                logo=Image(
                  'logo.png',
                  width=32,
                  alt='Logo'),
                brand=Text('Bootwrap').\
                  as_strong().\
                  as_light().\
                  ml(2),
                anchors=[
                    Anchor('Home').\
                    link('/'),
                    Anchor('About').\
                    link('/about')
                ], 
                actions=[
                    Button('Sign In').\
                    as_outline().\
                    as_light().\
                    link('/signin')
                ]
            )

    class MyPage(Page):
        def __init__(self, container):
            super().__init__(
                favicon = 'favicon.ico',
                title='Hello World Application',
                menu=MyMenu(),
                container=container
            )

    @app.route('/')
    def home():
        return Markup(
          MyPage(container=[
            Text('Home').as_heading(1)
            ]
          )
        )

    @app.route('/about')
    def about():
        return Markup(
          MyPage(container=[
            Text('About').as_heading(1)
          ]
        )
      )

    @app.route('/signin')
    def signin():
        return Markup(
          MyPage(
            container=[
              Text('Sign In').as_heading(1)
            ]
          )
        )

    if __name__ == '__main__':
        app.run(debug=True)
  image:
    file: multi-pages-app.png
    height: 200
